Add 'lock' parameter toggle switch
freeotp/freeotp.github.io pull request #16
Opened 2020-02-11 16:34 UTC by justin-stephenson

![Screenshot from 2020-02-11 11-29-29](https://user-images.githubusercontent.com/13416969/74257206-7fd12200-4cc2-11ea-82b0-a99d56209d82.png)
![Screenshot from 2020-02-11 11-29-34](https://user-images.githubusercontent.com/13416969/74257218-83fd3f80-4cc2-11ea-8a49-f6c010bd3538.png)

2020-02-14 15:05 UTC, justin-stephenson commented
![Screenshot from 2020-02-14 10-04-11](https://user-images.githubusercontent.com/13416969/74542357-6d005c80-4f11-11ea-8b56-a7785e73a747.png)

@npmccallum Fixed, new screenshot shown above.

2021-03-28 15:31 UTC, npmccallum requested changes
Code looks mostly good. However, the lock checkbox is getting wrapped. That should be fixed. The digits slider should take up all available space, but the `Lock []` should not wrap.

2021-03-29 13:49 UTC, npmccallum approved these changes

2021-03-29 13:50 UTC, merged

2021-07-16 10:10 UTC, hilari0n commented
Can anyone explain what the "lock" parameter is actually for? Is there any specification explaining its meaning?